# Generated by Django 3.1.12 on 2022-03-14 06:49

from django.db import migrations, models
import djongo.models.fields
import trojan_dining.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('meals', djongo.models.fields.ArrayField(model_container=trojan_dining.models.Meal)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_uuid', models.UUIDField(default=uuid.UUID('3caf9562-7532-4d49-8f13-3f0db39db434'), editable=False)),
                ('name', models.CharField(max_length=100)),
                ('allergens', djongo.models.fields.ArrayField(model_container=trojan_dining.models.Allergen)),
            ],
        ),
    ]
