# Generated by Django 4.0 on 2022-02-01 03:50

from django.db import migrations, models
import djongo.models.fields
import trojan_dining.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('meals', djongo.models.fields.ArrayField(model_container=trojan_dining.models.Meal)),
            ],
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('allergens', djongo.models.fields.ArrayField(model_container=trojan_dining.models.Allergen)),
            ],
        ),
    ]
