# Generated by Django 3.1.12 on 2022-03-14 07:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trojan_dining', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_uuid',
            field=models.UUIDField(default=uuid.UUID('7728e854-a4de-4723-9fee-b4603372a748'), editable=False),
        ),
    ]
