# Generated by Django 3.1.12 on 2022-06-20 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trojan_dining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='item_id',
            field=models.UUIDField(default=None),
        ),
    ]
