# Generated by Django 3.1.12 on 2022-06-27 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trojan_dining', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='item_uuid',
        ),
        migrations.AddField(
            model_name='subscription',
            name='item_id',
            field=models.UUIDField(default=None),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='phone_no',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
