# Generated by Django 4.0 on 2022-01-22 19:26

from django.db import migrations, models
import djongo.models.fields
import trojan_dining.models


class Migration(migrations.Migration):

    dependencies = [
        ('trojan_dining', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meals', djongo.models.fields.ArrayField(model_container=trojan_dining.models.Meal)),
            ],
        ),
        migrations.AddField(
            model_name='menuitem',
            name='allergens',
            field=djongo.models.fields.ArrayField(default=None, model_container=trojan_dining.models.Allergen),
            preserve_default=False,
        ),
    ]
