# Generated by Django 3.1.12 on 2022-03-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trojan_dining', '0002_auto_20220306_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='menu_date',
            field=models.DateField(default=None),
        ),
    ]
