# Generated by Django 3.1.12 on 2022-03-14 07:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trojan_dining', '0002_auto_20220314_0715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_uuid',
            field=models.UUIDField(default=uuid.UUID('bf8d9b52-cfc8-4332-810e-56ed0f5b5e57'), editable=False),
        ),
    ]
