# Generated by Django 3.1.12 on 2022-03-14 19:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('trojan_dining', '0003_auto_20220314_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_uuid',
            field=models.UUIDField(default=uuid.UUID('6c081f8e-ec37-4454-a4fd-426363bc2ad2'), editable=False),
        ),
    ]
