# Generated by Django 3.1.12 on 2022-03-15 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trojan_dining', '0004_auto_20220314_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='item_uuid',
            field=models.CharField(max_length=32),
        ),
    ]
