# Generated by Django 3.1.12 on 2022-06-11 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trojan_dining', '0005_auto_20220315_0243'),
        ('trojan_dining', '0004_auto_20220307_1755'),
    ]

    operations = [
    ]
