# Generated by Django 3.1.12 on 2022-06-13 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trojan_dining', '0007_remove_menu_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_uuid', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=100)),
                ('phone_no', models.CharField(max_length=100)),
            ],
        ),
    ]
